#!/bin/bash

# Initialize variables to store values
keywords=()
websites=()
log_file=""

# Parse options and their arguments
while getopts ":k:w:l:a" opt; do
    case ${opt} in
        k)
            keywords+=("$OPTARG")
            ;;
        w)
            websites+=("$OPTARG")
            ;;
        l)
            log_file="$OPTARG"
            ;;
        a)
            # Some action if -a is provided, you can add your logic here
            echo "Option -a specified"
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument"
            exit 1
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG"
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

# Output the collected data
echo "Keywords: ${keywords[@]}"
echo "Websites: ${websites[@]}"
echo "Log File: $log_file"
